
title: "CLASSICS 2480"
subtitle: "Roman Emperors"
author: "Arnav Goyal"
date: "2025-2026"
toc: true
numbersections: true
fontsize: 12pt
mainfont: "TeX Gyre Pagella"
monofont: "JetBrains Mono"
header-includes:
  - \input{../../../assets/preamble.tex}
  - \usepackage{etoolbox}
  - \preto{\tableofcontents}{\clearpage}
  - \apptocmd{\tableofcontents}{\clearpage}{}{}

